#!/bin/bash

#-------------------------------------------------------------------------------
#    Extract Section
#
# Read object file from stdin, extract named section and print its bit-pattern
#-------------------------------------------------------------------------------

SECTION="\s$1"; shift;
BASE=${1:-'-b'};

DIR=/tmp/extract-section
TEMP=$DIR/$(uuidgen).o

[ -d $DIR ] || mkdir $DIR

cat > $TEMP

if [[ $BASE == '-b' ]]; then
llvm-readobj -elf-output-style=GNU --sections $TEMP                           \
    | grep $SECTION                                                           \
    | awk '{print "dd if='$TEMP' bs=1 count=$[0x" $7 "] skip=$[0x" $6 "]"}'   \
    | bash 2> /dev/null                                                       \
    | xxd -bits -groupsize 0                                                  \
    | cut -d " " -f 2                                                         \
    | tr  -d "\n"                                                             \
    | fold -w8 | paste -sd'.' -                                               \
    | fold -w1 | paste -sd' ' -
elif [[ $BASE == '-h' ]]; then
llvm-readobj -elf-output-style=GNU --sections $TEMP                           \
    | grep $SECTION                                                           \
    | awk '{print "dd if='$TEMP' bs=1 count=$[0x" $7 "] skip=$[0x" $6 "]"}'   \
    | bash 2> /dev/null                                                       \
    | xxd -p                                                                  \
    | fold -w4 | paste -sd' ' -
fi

rm $TEMP
